# Generated by Django 5.1.1 on 2024-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_powerup_gamesession_power_up_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('challenge_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-date']},
        ),
    ]
